.TH INSPACT 1 inspact
.SH NAME
inspact \- spac file inspector
.SH SYNOPSIS
.B inspact
.I file
.B [...
.I files
.B ]
.SH DESCRIPTION
Inspects infos of provided paths as if they where spac files.

Infos will be printed to stdout, non conformance errors will be printed
to stderr
.SH SEE ALSO
spac(1) xspac(1)
